export const SET_ROUTE_NAME = "SET_ROUTE_NAME" 
export const SET_SINGER = "SET_SINGER"
export const SET_PLAYRADOM = 'SET_PLAYRADOM'
export const SET_SCREEN_SIZE = 'SET_SCREEN_SIZE'
export const SET_PLAY_LIST = 'SET_PLAY_LIST'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_STOP_PLAY = 'SET_STOP_PLAY'